source 'https://rubygems.org'
ruby '2.3.1'

gem 'bundler'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'pg'
gem 'rake'
gem 'rack-flash3'
gem 'bcrypt'
gem 'aescrypt'
gem 'sidekiq'
gem 'redis', '~>3.2'
gem 'rspec'
